---
title: "plot_diffMethPerChr"
author: "YC"
date: "11/9/2019"
output: html_document
---
```{r}
a <- diff_toba_covall_full_chrsel
qvalue.cutoff <- 0.05
meth.cutoff <- 10

```
```{r}
  x <- getData(diff_toba_covall_full_chrsel)
  temp.hyper = x[x$qvalue < 0.05 & x$meth.diff >=10, ]
  temp.hypo =x[x$qvalue < 0.05 & x$meth.diff <= -10,]
  dmc.hyper = 100 * nrow(temp.hyper)/nrow(x)
  dmc.hypo = 100 * nrow(temp.hypo)/nrow(x)
  all.hyper.hypo = data.frame(number.of.hypermethylated = nrow(temp.hyper), 
    percentage.of.hypermethylated = dmc.hyper, number.of.hypomethylated = nrow(temp.hypo), 
    percentage.of.hypomethylated = dmc.hypo)
  dmc.hyper.chr = merge(as.data.frame(table(temp.hyper$chr)), as.data.frame(table(x$chr)), by = "Var1")
  dmc.hyper.chr = cbind(dmc.hyper.chr, perc = 100 * dmc.hyper.chr[, 2]/dmc.hyper.chr[, 3])
  dmc.hypo.chr = merge(as.data.frame(table(temp.hypo$chr)), as.data.frame(table(x$chr)), by = "Var1")
  dmc.hypo.chr = cbind(dmc.hypo.chr, perc = 100 * dmc.hypo.chr[, 2]/dmc.hypo.chr[, 3])
  dmc.hyper.hypo = merge(dmc.hyper.chr[, c(1, 2, 4)], dmc.hypo.chr[, c(1, 2, 4)], by = "Var1")
  dmc.hyper.hypo = dmc.hyper.hypo[order(as.numeric(sub("chr", "", dmc.hyper.hypo$Var1))), ]
  names(dmc.hyper.hypo) = c("chr", "number.of.hypermethylated", "percentage.of.hypermethylated", "number.of.hypomethylated", "percentage.of.hypomethylated")
  
  barplot(t(as.matrix(data.frame(hyper = dmc.hyper.hypo[1:22, 3], hypo = dmc.hyper.hypo[1:22, 5], row.names = dmc.hyper.hypo[1:22,1]))), las = 1, horiz = TRUE, col = c("magenta", "aquamarine4"), main = paste("% of hyper & hypo methylated regions per chromosome", sep = ""), xlab = "% (percentage)")
  mtext(side = 3, paste("qvalue<", qvalue.cutoff, " & methylation diff. >=", meth.cutoff, " %", sep = ""))
  legend("topright", legend = c("hyper", "hypo"), fill = c("magenta", "aquamarine4"))
```


```{r}
findMethods(diffMethPerChr)
An object of class  “listOfMethods” 
$methylDiff
Method Definition:

function (x, plot = TRUE, qvalue.cutoff = 0.01, meth.cutoff = 25, 
    exclude = NULL, ...) 
{
    x = getData(x)
    temp.hyper = x[x$qvalue < qvalue.cutoff & x$meth.diff >= 
        meth.cutoff, ]
    temp.hypo = x[x$qvalue < qvalue.cutoff & x$meth.diff <= -meth.cutoff, 
        ]
    dmc.hyper = 100 * nrow(temp.hyper)/nrow(x)
    dmc.hypo = 100 * nrow(temp.hypo)/nrow(x)
    all.hyper.hypo = data.frame(number.of.hypermethylated = nrow(temp.hyper), 
        percentage.of.hypermethylated = dmc.hyper, number.of.hypomethylated = nrow(temp.hypo), 
        percentage.of.hypomethylated = dmc.hypo)
    dmc.hyper.chr = merge(as.data.frame(table(temp.hyper$chr)), 
        as.data.frame(table(x$chr)), by = "Var1")
    dmc.hyper.chr = cbind(dmc.hyper.chr, perc = 100 * dmc.hyper.chr[, 
        2]/dmc.hyper.chr[, 3])
    dmc.hypo.chr = merge(as.data.frame(table(temp.hypo$chr)), 
        as.data.frame(table(x$chr)), by = "Var1")
    dmc.hypo.chr = cbind(dmc.hypo.chr, perc = 100 * dmc.hypo.chr[, 
        2]/dmc.hypo.chr[, 3])
    dmc.hyper.hypo = merge(dmc.hyper.chr[, c(1, 2, 4)], dmc.hypo.chr[, 
        c(1, 2, 4)], by = "Var1")
    dmc.hyper.hypo = dmc.hyper.hypo[order(as.numeric(sub("chr", 
        "", dmc.hyper.hypo$Var1))), ]
    names(dmc.hyper.hypo) = c("chr", "number.of.hypermethylated", 
        "percentage.of.hypermethylated", "number.of.hypomethylated", 
        "percentage.of.hypomethylated")
    if (plot) {
        if (!is.null(exclude)) {
            dmc.hyper.hypo = dmc.hyper.hypo[!dmc.hyper.hypo$chr %in% 
                exclude, ]
        }
        barplot(t(as.matrix(data.frame(hyper = dmc.hyper.hypo[, 
            3], hypo = dmc.hyper.hypo[, 5], row.names = dmc.hyper.hypo[, 
            1]))), las = 2, horiz = TRUE, col = c("magenta", 
            "aquamarine4"), main = paste("% of hyper & hypo methylated regions per chromosome", 
            sep = ""), xlab = "% (percentage)", ...)
        mtext(side = 3, paste("qvalue<", qvalue.cutoff, " & methylation diff. >=", 
            meth.cutoff, " %", sep = ""))
        legend("topright", legend = c("hyper", "hypo"), fill = c("magenta", 
            "aquamarine4"))
    }
    else {
        list(diffMeth.per.chr = dmc.hyper.hypo, diffMeth.all = all.hyper.hypo)
    }
}
<bytecode: 0x13758abc8>
<environment: namespace:methylKit>

Signatures:
        x           
target  "methylDiff"
defined "methylDiff"

$methylDiffDB
Method Definition:

function (x, plot = TRUE, qvalue.cutoff = 0.01, meth.cutoff = 25, 
    exclude = NULL, ...) 
{
    diffMeth <- function(data, qvalue.cutoff, meth.cutoff) {
        .setMethylDBNames(data, "methylDiffDB")
        temp.hyper = data[data$qvalue < qvalue.cutoff & data$meth.diff >= 
            meth.cutoff, ]
        temp.hypo = data[data$qvalue < qvalue.cutoff & data$meth.diff <= 
            -meth.cutoff, ]
        dmc.hyper.chr = merge(as.data.frame(table(temp.hyper$chr)), 
            as.data.frame(table(data$chr)), by = "Var1")
        dmc.hyper.chr = cbind(dmc.hyper.chr, perc = 100 * dmc.hyper.chr[, 
            2]/dmc.hyper.chr[, 3])
        dmc.hypo.chr = merge(as.data.frame(table(temp.hypo$chr)), 
            as.data.frame(table(data$chr)), by = "Var1")
        dmc.hypo.chr = cbind(dmc.hypo.chr, perc = 100 * dmc.hypo.chr[, 
            2]/dmc.hypo.chr[, 3])
        dmc.hyper.hypo = merge(dmc.hyper.chr[, c(1, 2, 4)], dmc.hypo.chr[, 
            c(1, 2, 4)], by = "Var1", all = TRUE)
        names(dmc.hyper.hypo) = c("chr", "number.of.hypermethylated", 
            "percentage.of.hypermethylated", "number.of.hypomethylated", 
            "percentage.of.hypomethylated")
        return(dmc.hyper.hypo)
    }
    res <- applyTbxByChr(x@dbpath, return.type = "data.frame", 
        FUN = diffMeth, qvalue.cutoff = qvalue.cutoff, meth.cutoff = meth.cutoff)
    dmc.hyper = 100 * sum(res$number.of.hypermethylated)/x@num.records
    dmc.hypo = 100 * sum(res$number.of.hypomethylated)/x@num.records
    all.hyper.hypo = data.frame(number.of.hypermethylated = sum(res$number.of.hypermethylated), 
        percentage.of.hypermethylated = dmc.hyper, number.of.hypomethylated = sum(res$number.of.hypomethylated), 
        percentage.of.hypomethylated = dmc.hypo)
    dmc.hyper.hypo = res[order(as.numeric(sub("chr", "", res$chr))), 
        ]
    if (plot) {
        if (!is.null(exclude)) {
            dmc.hyper.hypo = dmc.hyper.hypo[!dmc.hyper.hypo$chr %in% 
                exclude, ]
        }
        barplot(t(as.matrix(data.frame(hyper = dmc.hyper.hypo[, 
            3], hypo = dmc.hyper.hypo[, 5], row.names = dmc.hyper.hypo[, 
            1]))), las = 2, horiz = TRUE, col = c("magenta", 
            "aquamarine4"), main = paste("% of hyper & hypo methylated regions per chromosome", 
            sep = ""), xlab = "% (percentage)", ...)
        mtext(side = 3, paste("qvalue<", qvalue.cutoff, " & methylation diff. >=", 
            meth.cutoff, " %", sep = ""))
        legend("topright", legend = c("hyper", "hypo"), fill = c("magenta", 
            "aquamarine4"))
    }
    else {
        list(diffMeth.per.chr = dmc.hyper.hypo, diffMeth.all = all.hyper.hypo)
    }
}
<bytecode: 0x137590810>
<environment: namespace:methylKit>

Signatures:
        x             
target  "methylDiffDB"
defined "methylDiffDB"

Slot arguments:
[1] "x"             "plot"          "qvalue.cutoff" "meth.cutoff"   "exclude"      
Slot signatures:
[[1]]
[1] "methylDiff"

[[2]]
[1] "methylDiffDB"

Slot generic:
standardGeneric for "diffMethPerChr" defined from package "methylKit"

function (x, plot = TRUE, qvalue.cutoff = 0.01, meth.cutoff = 25, 
    exclude = NULL, ...) 
standardGeneric("diffMethPerChr")
<bytecode: 0x137581000>
<environment: 0x137543ac8>
Methods may be defined for arguments: x, plot, qvalue.cutoff, meth.cutoff, exclude
Use  showMethods("diffMethPerChr")  for currently available ones.
> 
```

